#!/bin/bash


function transl(){
    docker-compose exec php bash -c "php public_photo_booth/index.php cli translate $1";
}

function dev(){
    docker-compose up -d;
    npm run watch;
}

function down(){
    docker-compose down;
}

function restart(){
    docker-compose down;
    docker-compose up -d;
#    npm run watch;
}

function ssh(){
    docker-compose exec php bash;
}

function release(){

    rm -Rf public_photo_booth/assets/fonts
    rm -Rf public_photo_booth/assets/images

    rm -Rf releases/assets/fonts
    rm -Rf releases/assets/images

    npm ci;
    npm run build:prod;

    mkdir -p -m a=rwx -p releases/tmp;

    rm -Rf releases/tmp/*

    echo "Make folders"

    mkdir -p -m a=rwx releases/tmp/writable/models
    mkdir -p -m a=rwx releases/tmp/writable/session
    mkdir -p -m a=rwx releases/tmp/writable/logs
    mkdir -p -m a=rwx releases/tmp/writable/uploads/images

    echo "Copy files"

    cp -r app releases/tmp/
    cp -r public_photo_booth releases/tmp/
    cp -r public_sharing releases/tmp/
    cp -r vendor releases/tmp/

    cp -r writable/models/app_models_email_config_model.ser releases/tmp/writable/models/
    cp -r writable/models/app_models_sharing_config_model.ser releases/tmp/writable/models/
    cp -r writable/models/app_models_translations_model.ser releases/tmp/writable/models/

    echo "Renaming result"

    rm -Rf releases/$1
    mv releases/tmp/ releases/$1

    echo "Creating zip archive"

    rm -Rf releases/$1.zip
    zip -r releases/$1.zip releases/$1

    echo "================ DONE ================"
}

$1 $2 $3 $4 $5