version: '2'

services:
    php:
        image: bitnami/php-fpm:7.3.25
        ports:
            - 9000:9000
        volumes:
            - ./:/app
        networks:
            - backbone

    apache:
        image: bitnami/apache:latest
        ports:
            - 80:8080
        volumes:
            - ./config/vhosts.conf:/vhosts/myapp.conf:ro
            - ./:/app
        depends_on:
            - php
        networks:
            - backbone

networks:
    backbone:
        driver: bridge