<?php namespace App\Controllers;

use App\Models\EmailConfigModel;
use CodeIgniter\RESTful\ResourceController;

class ApiController extends ResourceController
{
	public function sendEmail(){

        $emailModel = new EmailConfigModel();

        $emailModel->enabled = true;
        $emailModel->host = '0.0.0.0';
        $emailModel->username = 'test';

        $emailModel->save();

        $emailModelLoaded = EmailConfigModel::findOne();
        if($emailModelLoaded){
            $emailModelLoaded->delete();
        }

        var_dump(EmailConfigModel::findAll());

	}

    /**
     * 1) screenshot is taken
     * 2) uploaded with uploadImage
     * 3) uploadImage return upload status and unique id
     * 4) qr code is generated by this unique id
     */
	public function uploadImage(){

	}

	public function getQRCode(){

    }
}
